package types

// Default values for each flag.
const (
	DefaultRunnerLabel  = "gh-secret-kit-migrate"
	DefaultWorkflowName = "gh-secret-kit-migrate"
	DefaultBranch       = "gh-secret-kit-migrate"
	DefaultLabel        = "gh-secret-kit-migrate"
	// DefaultDumpWorkflowName is the target-specified mode workflow file name
	// (without extension) for the undocumented "migrate repo dump" command.
	DefaultDumpWorkflowName = "gh-secret-kit-dump"
	// DefaultCopyWorkflowName is the workflow file name (without extension)
	// generated by the "secret copy" command.
	DefaultCopyWorkflowName = "gh-secret-kit-copy"
	// DefaultCopyRunnerLabel targets a GitHub-hosted runner, which is enough for
	// "secret copy" because the destination token is provided as a secret.
	DefaultCopyRunnerLabel = "ubuntu-latest"
	// DefaultCopyTokenSecretName is the base name of the temporary source
	// repository secret holding the destination token.
	DefaultCopyTokenSecretName = "GH_SECRET_KIT_COPY_TOKEN"
	// DefaultCodespacesCopyTokenEnvName is the base name of the environment
	// variable holding the destination token inside the codespace created by
	// the "secret codespaces copy" command.
	DefaultCodespacesCopyTokenEnvName = "GH_SECRET_KIT_COPY_TOKEN"
	// DefaultCodespacesCopyIdleTimeout keeps the ephemeral codespace short-lived
	// in case the copy is interrupted before the cleanup runs.
	DefaultCodespacesCopyIdleTimeout = "5m"
	// DefaultCodespacesCopyRetentionPeriod bounds how long a stopped ephemeral
	// codespace is kept when the cleanup could not delete it.
	DefaultCodespacesCopyRetentionPeriod = "1h"
	// DefaultAgentsCopyTokenSecretName is the base name of the temporary Agents
	// secret holding the destination token inside the Copilot coding agent
	// environment started by the "secret agents copy" command.
	DefaultAgentsCopyTokenSecretName = "GH_SECRET_KIT_COPY_TOKEN"
	// DefaultAgentsCopyBranch is the prefix of the temporary branch that carries
	// the copilot-setup-steps workflow and is made the default branch while the
	// "secret agents copy" command runs.
	DefaultAgentsCopyBranch = "gh-secret-kit-copy"
	// DefaultAgentsCopyPrompt tells the Copilot coding agent that it has nothing
	// to do, because the copy runs in the setup steps before the agent starts.
	DefaultAgentsCopyPrompt = "Do not change anything in this repository. The requested maintenance already ran in the setup steps. Reply that there is nothing to do and stop."
	// DefaultAgentsCopyTimeout bounds how long the copy waits for the Copilot
	// coding agent environment to run the setup steps.
	DefaultAgentsCopyTimeout = "30m"
	// DefaultDependabotCopyTokenSecretName is the base name of the temporary
	// Dependabot secret holding the destination token inside the
	// Dependabot-triggered workflow run started by the
	// "secret dependabot copy" command.
	DefaultDependabotCopyTokenSecretName = "GH_SECRET_KIT_COPY_TOKEN"
	// DefaultDependabotCopyBranch is the prefix of the temporary branch that
	// carries the copy workflow and is made the default branch while the
	// "secret dependabot copy" command runs.
	DefaultDependabotCopyBranch = "gh-secret-kit-dependabot-copy"
	// DefaultDependabotCopyTimeout bounds how long the copy waits for
	// Dependabot to check for updates and push the branch that runs the copy
	// workflow. The check is scheduled by GitHub and can take several minutes.
	DefaultDependabotCopyTimeout = "30m"
)

// CommonOptions holds common options for migrate commands
type CommonOptions struct {
	Source                 string
	Destination            string
	SourceEnv              string
	DestinationEnv         string
	Secrets                []string
	Rename                 []string
	Overwrite              bool
	DestinationTokenSecret string
}

// RunnerOptions holds options for runner commands
type RunnerOptions struct {
	RunnerLabel string
	RunnerGroup string
	MaxRunners  int
}

// WorkflowOptions holds options for workflow commands
type WorkflowOptions struct {
	RunnerLabel  string
	WorkflowName string
	Branch       string
	Label        string
	Wait         bool
	Timeout      string
}
